# Generated by Django 5.1.11 on 2026-02-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_rejection_reason_article_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
