# Generated by Django 5.1.11 on 2026-02-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="featured_image",
        ),
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
