# Generated by Django 6.0 on 2025-12-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified_delegate",
        ),
        migrations.AddField(
            model_name="user",
            name="is_restricted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("JR", "Junior (Elementary/JH)"),
                    ("SR", "Senior (HS/College)"),
                    ("AD", "Moderator/Admin"),
                ],
                default="SR",
                max_length=2,
            ),
        ),
    ]
