# Generated by Django 6.0 on 2026-03-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("SPEECH", "Speech & Public Speaking"),
                            ("DRAFT", "Draft Resolution Writing"),
                            ("NEGOTIATION", "Negotiation & Diplomacy"),
                            ("RESEARCH", "Research & Position Papers"),
                            ("PROCEDURE", "Rules of Procedure"),
                            ("GENERAL", "General MUN Skills"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="📚",
                        help_text="Emoji icon for the category",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Curriculum Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField(help_text="Lesson content in markdown")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEG", "Beginner"),
                            ("INT", "Intermediate"),
                            ("ADV", "Advanced"),
                        ],
                        default="BEG",
                        max_length=3,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("estimated_minutes", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="curriculum.curriculumcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PracticeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("SPEECH", "Speech Prompt"),
                            ("DRAFT", "Draft Resolution Exercise"),
                            ("NEGOTIATION", "Negotiation Scenario"),
                            ("QUIZ", "Multiple Choice Quiz"),
                            ("OPEN", "Open-Ended Question"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "prompt",
                    models.TextField(help_text="The question or scenario prompt"),
                ),
                (
                    "sample_answer",
                    models.TextField(
                        blank=True,
                        help_text="Optional sample/ideal answer for AI reference",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEG", "Beginner"),
                            ("INT", "Intermediate"),
                            ("ADV", "Advanced"),
                        ],
                        default="BEG",
                        max_length=3,
                    ),
                ),
                (
                    "hints",
                    models.TextField(
                        blank=True, help_text="Optional hints for the student"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="curriculum.curriculumcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text Submission"),
                            ("FILE", "File Upload"),
                            ("VIDEO_URL", "Video URL"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, help_text="For draft resolutions or text answers"
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="curriculum/uploads/%Y/%m/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="URL to uploaded speech video"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("REVIEWED", "AI Reviewed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="curriculum.curriculumcategory",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="curriculum.practicequestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score out of 100"
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("improvements", models.TextField(blank=True)),
                ("detailed_feedback", models.TextField(blank=True)),
                (
                    "suggestions",
                    models.TextField(blank=True, help_text="Actionable next steps"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="curriculum.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Feedback",
                "verbose_name_plural": "AI Feedback",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Progress",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
