# Generated by Django 6.0 on 2026-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicequestion",
            options={"ordering": ["-is_seeded", "-created_at"]},
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="is_seeded",
            field=models.BooleanField(
                default=False, help_text="True for hand-curated/pre-seeded questions"
            ),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="key_concepts",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated key MUN concepts this question tests",
            ),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="quality_score",
            field=models.FloatField(
                blank=True,
                help_text="Quality rating 0-5 for future curation",
                null=True,
            ),
        ),
    ]
