# Generated by Django 5.1.11 on 2026-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_alter_practicequestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifeedback",
            name="example_revision",
            field=models.TextField(
                blank=True,
                help_text="AI-rewritten example of the student's weakest section",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="rubric_scores",
            field=models.JSONField(
                blank=True,
                help_text="Per-criterion rubric breakdown: {criterion: {score, max, comment}}",
                null=True,
            ),
        ),
    ]
