# Generated by Django 5.1.11 on 2026-03-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_aifeedback_example_revision_aifeedback_rubric_scores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MUNTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="The tip text")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SPEECH", "Speech & Public Speaking"),
                            ("DRAFT", "Draft Resolution Writing"),
                            ("NEGOTIATION", "Negotiation & Diplomacy"),
                            ("RESEARCH", "Research & Position Papers"),
                            ("PROCEDURE", "Rules of Procedure"),
                            ("GENERAL", "General MUN Skills"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEG", "Beginner"),
                            ("INT", "Intermediate"),
                            ("ADV", "Advanced"),
                        ],
                        default="BEG",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MUN Tip",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("general", "General Chat"),
                            ("simulation", "Scenario Simulation"),
                        ],
                        default="general",
                        max_length=12,
                    ),
                ),
                (
                    "simulation_config",
                    models.JSONField(
                        blank=True,
                        help_text='{"role": "opposing_delegate", "country": "...", "topic": "...", "stance": "..."}',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="curriculum.practicequestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
