# Generated by Django 5.1.11 on 2026-03-16 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_muntip_chatsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="Which endpoint triggered this call", max_length=100
                    ),
                ),
                (
                    "estimated_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated total tokens used"
                    ),
                ),
                ("model_name", models.CharField(default="gpt-4o-mini", max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage Log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
