# Generated by Django 5.1.11 on 2026-03-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0006_apiusagelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("best_score", models.PositiveIntegerField(default=0)),
                ("total_practice_time_minutes", models.PositiveIntegerField(default=0)),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("longest_streak_days", models.PositiveIntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "scores_by_category",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"SPEECH": {"avg": 75, "count": 5, "total": 375}, ...}',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Stats",
                "verbose_name_plural": "User Stats",
            },
        ),
    ]
