# Generated by Django 5.1.11 on 2026-03-28 01:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0007_userstats"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lesson",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "content", config="english"
                ),
                name="lesson_search_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practicequestion",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "prompt", config="english"
                ),
                name="question_search_idx",
            ),
        ),
    ]
