# Generated by Django 5.1.11 on 2026-03-28 01:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "name", "city", "country", config="english"
                ),
                name="conference_search_idx",
            ),
        ),
    ]
